!SESSION 2016-02-14 18:51:11.211 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

This is a continuation of log file /var/webserver/workspace/.metadata/.bak_0.log
Created Time: 2016-02-15 16:38:27.092

!ENTRY org.eclipse.search 4 0 2016-02-15 16:38:27.092
!MESSAGE Problems encountered during text search.
!SUBENTRY 1 org.eclipse.search 4 4 2016-02-15 16:38:27.092
!MESSAGE File 'JokrBackend/JokrBackend/gunicorn.sock' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/gunicorn.sock'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/gunicorn.sock'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-02-15 16:38:27.092
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/gunicorn.sock'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-02-15 16:38:27.095
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/management/commands/__pycache__/ModTop.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/management/commands/__pycache__/ModTop.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/management/commands/__pycache__/ModTop.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-02-15 16:38:27.095
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/management/commands/__pycache__/ModTop.cpython-34.pyc'.

!ENTRY org.python.pydev.shared_core 4 4 2016-02-15 16:40:06.387
!MESSAGE Unable to get project for the run
!STACK 1
org.eclipse.core.runtime.CoreException: Unable to get project for the run
	at org.python.pydev.debug.ui.launching.PythonRunnerConfig.getProjectFromConfiguration(PythonRunnerConfig.java:335)
	at org.python.pydev.debug.ui.launching.PythonRunnerConfig.getPythonpathFromConfiguration(PythonRunnerConfig.java:359)
	at org.python.pydev.debug.ui.blocks.PythonPathBlock.initializeFrom(PythonPathBlock.java:94)
	at org.python.pydev.debug.ui.MainModuleTab.initializeFrom(MainModuleTab.java:87)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTabGroup.initializeFrom(AbstractLaunchConfigurationTabGroup.java:86)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupWrapper.initializeFrom(LaunchConfigurationTabGroupWrapper.java:194)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.displayInstanceTabs(LaunchConfigurationTabGroupViewer.java:753)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer$8.run(LaunchConfigurationTabGroupViewer.java:624)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.inputChanged(LaunchConfigurationTabGroupViewer.java:641)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput0(LaunchConfigurationTabGroupViewer.java:603)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.setInput(LaunchConfigurationTabGroupViewer.java:579)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.handleLaunchConfigurationSelectionChanged(LaunchConfigurationsDialog.java:941)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog$3.selectionChanged(LaunchConfigurationsDialog.java:560)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:888)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:886)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1726)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1139)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView.handleConfigurationAdded(LaunchConfigurationView.java:283)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView.access$1(LaunchConfigurationView.java:272)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationView$2.run(LaunchConfigurationView.java:261)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.open(LaunchConfigurationsDialog.java:1132)
	at org.eclipse.debug.ui.DebugUITools$2.run(DebugUITools.java:600)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:608)
	at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:542)
	at org.eclipse.debug.ui.actions.OpenLaunchDialogAction.run(OpenLaunchDialogAction.java:81)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1276)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3562)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3186)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
!SUBENTRY 1 org.python.pydev.debug 4 4 2016-02-15 16:40:06.387
!MESSAGE Unable to get project for the run

!ENTRY org.python.pydev.shared_core 4 4 2016-02-15 16:48:51.950
!MESSAGE No message gotten (null message).
!STACK 0
java.lang.NullPointerException
	at org.python.pydev.parser.prettyprinterv2.MakeAstValidForPrettyPrintingVisitor.visitTryExcept(MakeAstValidForPrettyPrintingVisitor.java:537)
	at org.python.pydev.parser.jython.ast.TryExcept.accept(TryExcept.java:108)
	at org.python.pydev.parser.prettyprinterv2.MakeAstValidForPrettyPrintingVisitor.visitFunctionDef(MakeAstValidForPrettyPrintingVisitor.java:862)
	at org.python.pydev.parser.jython.ast.FunctionDef.accept(FunctionDef.java:131)
	at org.python.pydev.parser.prettyprinterv2.MakeAstValidForPrettyPrintingVisitor.makeValid(MakeAstValidForPrettyPrintingVisitor.java:171)
	at org.python.pydev.editor.hover.PyTextHover.getDocstringHover(PyTextHover.java:230)
	at org.python.pydev.editor.hover.PyTextHover.getHoverInfo(PyTextHover.java:142)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:168)
!SESSION 2016-02-16 03:14:20.683 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-16 03:14:35.773
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-16 03:14:35.773
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-02-18 00:14:14.350 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-18 22:23:36.820
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-18 22:23:36.820
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-02-21 18:35:11.552 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-22 21:24:17.754
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-22 21:24:17.754
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.eclipse.debug.core 4 125 2016-02-22 21:25:58.748
!MESSAGE Invalid expression entry encountered while loading watch expressions. Expression text is empty.
!SESSION 2016-02-23 00:12:50.335 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /var/webserver/workspace -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-23 00:13:35.581
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-23 00:13:35.581
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-02-24 20:28:23.029 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-24 20:29:41.315
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-24 20:29:41.315
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-02-25 15:15:43.883 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-25 15:17:08.209
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-25 15:17:08.209
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 15:28:03.220
!MESSAGE Unable to read contents from: /var/webserver/workspace/.metadata/.plugins/org.python.pydev/v1_2zg0560313osl3vxy5rx43ffg/shell/bui_27169ea1jqm2cvfz50fc7nlh1.top
!STACK 0
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:264)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:254)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:163)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:78)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:90)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getCached(CompiledModule.java:295)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:158)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:325)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:1)
	at org.python.pydev.editor.codecompletion.revisited.ProjectModulesManager.getModuleAndRelatedModulesManager(ProjectModulesManager.java:193)
	at org.python.pydev.editor.codecompletion.revisited.ProjectModulesManager.getModule(ProjectModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getModule(AbstractASTManager.java:450)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1079)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:969)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:951)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:664)
	at org.python.pydev.editor.codecompletion.revisited.modules.AbstractModule.findDefinition(AbstractModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:177)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:79)
	at org.python.pydev.editor.hover.PyTextHover.getDocstringHover(PyTextHover.java:198)
	at org.python.pydev.editor.hover.PyTextHover.getHoverInfo(PyTextHover.java:142)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:168)

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 16:32:59.128
!MESSAGE Marker id 150179 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 150179 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:98)
	at org.python.pydev.debug.model.PyBreakpoint.getType(PyBreakpoint.java:155)
	at org.python.pydev.debug.model.AbstractDebugTarget.breakpointRemoved(AbstractDebugTarget.java:352)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.run(BreakpointManager.java:995)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.notify(BreakpointManager.java:1018)
	at org.eclipse.debug.internal.core.BreakpointManager.fireUpdate(BreakpointManager.java:932)
	at org.eclipse.debug.internal.core.BreakpointManager.removeBreakpoints(BreakpointManager.java:503)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointManagerVisitor.update(BreakpointManager.java:754)
	at org.eclipse.debug.internal.core.BreakpointManager.resourceChanged(BreakpointManager.java:688)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:146)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.core.resources 4 376 2016-02-25 16:32:59.129
!MESSAGE Marker id 150179 not found.
!SESSION 2016-02-25 16:45:34.507 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-25 16:55:17.849
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-25 16:55:17.849
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 17:02:57.821
!MESSAGE No message gotten (null message).
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1055)
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1182)
	at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:137)
	at org.eclipse.jface.text.AbstractDocument.getLineInformation(AbstractDocument.java:929)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineInformation(SynchronizableDocument.java:337)
	at org.python.pydev.shared_core.string.TextSelectionUtils.getStartLine(TextSelectionUtils.java:164)
	at org.python.pydev.editor.refactoring.RefactoringRequest.getBeginCol(RefactoringRequest.java:201)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:76)
	at com.python.pydev.refactoring.refactorer.RefactorerFindDefinition.findDefinition(RefactorerFindDefinition.java:61)
	at com.python.pydev.refactoring.refactorer.Refactorer.findDefinition(Refactorer.java:114)
	at com.python.pydev.refactoring.wizards.rename.PyReferenceSearcher.prepareSearch(PyReferenceSearcher.java:106)
	at com.python.pydev.refactoring.markoccurrences.MarkOccurrencesJob.createRequest(MarkOccurrencesJob.java:147)
	at org.python.pydev.shared_ui.mark_occurrences.BaseMarkOccurrencesJob.run(BaseMarkOccurrencesJob.java:168)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 17:17:44.120
!MESSAGE Marker id 150275 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 150275 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:98)
	at org.python.pydev.debug.model.PyBreakpoint.getType(PyBreakpoint.java:155)
	at org.python.pydev.debug.model.AbstractDebugTarget.breakpointRemoved(AbstractDebugTarget.java:352)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.run(BreakpointManager.java:995)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.notify(BreakpointManager.java:1018)
	at org.eclipse.debug.internal.core.BreakpointManager.fireUpdate(BreakpointManager.java:932)
	at org.eclipse.debug.internal.core.BreakpointManager.removeBreakpoints(BreakpointManager.java:503)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointManagerVisitor.update(BreakpointManager.java:754)
	at org.eclipse.debug.internal.core.BreakpointManager.resourceChanged(BreakpointManager.java:688)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:146)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.core.resources 4 376 2016-02-25 17:17:44.121
!MESSAGE Marker id 150275 not found.
!SESSION 2016-02-25 18:08:21.202 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-25 18:09:08.092
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-25 18:09:08.093
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 18:41:33.476
!MESSAGE Marker id 150552 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 150552 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:98)
	at org.python.pydev.debug.model.PyBreakpoint.getType(PyBreakpoint.java:155)
	at org.python.pydev.debug.model.AbstractDebugTarget.breakpointRemoved(AbstractDebugTarget.java:352)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.run(BreakpointManager.java:995)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.notify(BreakpointManager.java:1018)
	at org.eclipse.debug.internal.core.BreakpointManager.fireUpdate(BreakpointManager.java:932)
	at org.eclipse.debug.internal.core.BreakpointManager.removeBreakpoints(BreakpointManager.java:503)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointManagerVisitor.update(BreakpointManager.java:754)
	at org.eclipse.debug.internal.core.BreakpointManager.resourceChanged(BreakpointManager.java:688)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:146)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.core.resources 4 376 2016-02-25 18:41:33.478
!MESSAGE Marker id 150552 not found.

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 18:41:33.479
!MESSAGE Marker id 150553 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 150553 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:98)
	at org.python.pydev.debug.model.PyBreakpoint.getType(PyBreakpoint.java:155)
	at org.python.pydev.debug.model.AbstractDebugTarget.breakpointRemoved(AbstractDebugTarget.java:352)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.run(BreakpointManager.java:995)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.notify(BreakpointManager.java:1018)
	at org.eclipse.debug.internal.core.BreakpointManager.fireUpdate(BreakpointManager.java:932)
	at org.eclipse.debug.internal.core.BreakpointManager.removeBreakpoints(BreakpointManager.java:503)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointManagerVisitor.update(BreakpointManager.java:754)
	at org.eclipse.debug.internal.core.BreakpointManager.resourceChanged(BreakpointManager.java:688)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:146)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.core.resources 4 376 2016-02-25 18:41:33.479
!MESSAGE Marker id 150553 not found.

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 18:41:33.480
!MESSAGE Marker id 150554 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 150554 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:98)
	at org.python.pydev.debug.model.PyBreakpoint.getType(PyBreakpoint.java:155)
	at org.python.pydev.debug.model.AbstractDebugTarget.breakpointRemoved(AbstractDebugTarget.java:352)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.run(BreakpointManager.java:995)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.notify(BreakpointManager.java:1018)
	at org.eclipse.debug.internal.core.BreakpointManager.fireUpdate(BreakpointManager.java:932)
	at org.eclipse.debug.internal.core.BreakpointManager.removeBreakpoints(BreakpointManager.java:503)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointManagerVisitor.update(BreakpointManager.java:754)
	at org.eclipse.debug.internal.core.BreakpointManager.resourceChanged(BreakpointManager.java:688)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:146)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.core.resources 4 376 2016-02-25 18:41:33.481
!MESSAGE Marker id 150554 not found.

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 18:41:33.481
!MESSAGE Marker id 150555 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 150555 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:98)
	at org.python.pydev.debug.model.PyBreakpoint.getType(PyBreakpoint.java:155)
	at org.python.pydev.debug.model.AbstractDebugTarget.breakpointRemoved(AbstractDebugTarget.java:352)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.run(BreakpointManager.java:995)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.notify(BreakpointManager.java:1018)
	at org.eclipse.debug.internal.core.BreakpointManager.fireUpdate(BreakpointManager.java:932)
	at org.eclipse.debug.internal.core.BreakpointManager.removeBreakpoints(BreakpointManager.java:503)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointManagerVisitor.update(BreakpointManager.java:754)
	at org.eclipse.debug.internal.core.BreakpointManager.resourceChanged(BreakpointManager.java:688)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:146)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.core.resources 4 376 2016-02-25 18:41:33.481
!MESSAGE Marker id 150555 not found.

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 18:41:33.481
!MESSAGE Marker id 150556 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 150556 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:98)
	at org.python.pydev.debug.model.PyBreakpoint.getType(PyBreakpoint.java:155)
	at org.python.pydev.debug.model.AbstractDebugTarget.breakpointRemoved(AbstractDebugTarget.java:352)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.run(BreakpointManager.java:995)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.notify(BreakpointManager.java:1018)
	at org.eclipse.debug.internal.core.BreakpointManager.fireUpdate(BreakpointManager.java:932)
	at org.eclipse.debug.internal.core.BreakpointManager.removeBreakpoints(BreakpointManager.java:503)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointManagerVisitor.update(BreakpointManager.java:754)
	at org.eclipse.debug.internal.core.BreakpointManager.resourceChanged(BreakpointManager.java:688)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:146)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.core.resources 4 376 2016-02-25 18:41:33.481
!MESSAGE Marker id 150556 not found.
!SESSION 2016-02-25 20:20:52.828 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.python.pydev.shared_core 4 4 2016-02-25 20:36:21.592
!MESSAGE ERROR reading shell.
ProcessInfo:

 - Executed: /var/webserver/env/bin/python -u /home/nick/.eclipse/org.eclipse.platform_3.8_155965261/plugins/org.python.pydev_4.0.0.201504132356/pysrc/pycompletionserver.py 56210

 - Environment:
CLUTTER_IM_MODULE=xim
COMPIZ_BIN_PATH=/usr/bin/
COMPIZ_CONFIG_PROFILE=ubuntu
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-eH44EJIvXq
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
DESKTOP_SESSION=ubuntu
DISPLAY=:0
GDMSESSION=ubuntu
GDM_LANG=en_US
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/eclipse.desktop
GIO_LAUNCHED_DESKTOP_FILE_PID=5426
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-QzUS6I
GNOME_KEYRING_PID=1946
GPG_AGENT_INFO=/run/user/1000/keyring-QzUS6I/gpg:0:1
GTK_IM_MODULE=ibus
GTK_MODULES=overlay-scrollbar:unity-gtk-module
HOME=/home/nick
IM_CONFIG_PHASE=1
INSTANCE=
JOB=dbus
LANG=en_US.UTF-8
LANGUAGE=en_US
LOGNAME=nick
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/home/nick
PYTHONPATH=/home/nick/.eclipse/org.eclipse.platform_3.8_155965261/plugins/org.python.pydev_4.0.0.201504132356/pysrc/pydev_sitecustomize:/var/webserver/env/lib/python3.4:/var/webserver/env/lib/python3.4/plat-x86_64-linux-gnu:/var/webserver/env/lib/python3.4/lib-dynload:/usr/lib/python3.4:/usr/lib/python3.4/plat-x86_64-linux-gnu:/var/webserver/env/local/lib/python3.4/site-packages:/var/webserver/env/lib/python3.4/site-packages:/var/webserver/env/lib/python2.7/site-packages:/var/webserver/env/lib/python3.4/site-packages/pymysql:/var/webserver/env/local/lib/python3.4/site-packages/prettytable-0.7.2-py3.4.egg:/var/webserver/env/lib/python3.4/site-packages/prettytable-0.7.2-py3.4.egg
QT4_IM_MODULE=xim
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=appmenu-qt5
SELINUX_INIT=YES
SESSION=ubuntu
SESSIONTYPE=gnome-session
SESSION_MANAGER=local/nick-server-dev:@/tmp/.ICE-unix/2168,unix/nick-server-dev:/tmp/.ICE-unix/2168
SHELL=/bin/bash
SHLVL=0
SSH_AUTH_SOCK=/run/user/1000/keyring-QzUS6I/ssh
TEXTDOMAIN=im-config
TEXTDOMAINDIR=/usr/share/locale/
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1950
USER=nick
XAUTHORITY=/home/nick/.Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
XDG_CURRENT_DESKTOP=Unity
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/nick
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_ID=c2
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_VTNR=7
XMODIFIERS=@im=ibus

 - Working Dir:
/home/nick/.eclipse/org.eclipse.platform_3.8_155965261/plugins/org.python.pydev_4.0.0.201504132356/pysrc

 - OS:
Linux

 - Std output:


 - Err output:

!STACK 0
java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:497)
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
	at java.nio.channels.Channels.writeFully(Channels.java:98)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.write(AbstractShell.java:544)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:691)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.internalChangePythonPath(AbstractShell.java:737)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getImportCompletions(AbstractShell.java:755)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createInnerFromServer(CompiledModule.java:331)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.getGlobalTokens(CompiledModule.java:531)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:732)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:557)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:526)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:518)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:509)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.internalGenerateGetCompletionsForModule(AbstractASTManager.java:740)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:557)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:526)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getCompletionsForModule(AbstractASTManager.java:518)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findGlobalTokDef(SourceModule.java:1020)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinitionsFromModAndTok(SourceModule.java:969)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:951)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:788)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:664)
	at org.python.pydev.editor.codecompletion.revisited.modules.AbstractModule.findDefinition(AbstractModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:177)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:79)
	at org.python.pydev.editor.hover.PyTextHover.getDocstringHover(PyTextHover.java:198)
	at org.python.pydev.editor.hover.PyTextHover.getHoverInfo(PyTextHover.java:142)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:168)

!ENTRY org.eclipse.jface 2 0 2016-02-25 20:50:32.911
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-25 20:50:32.911
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-02-25 21:14:02.177 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-25 21:31:16.793
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-25 21:31:16.793
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-02-26 15:39:03.203 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-26 15:40:07.621
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-26 15:40:07.621
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-02-28 23:23:24.516 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2016-02-28 23:23:26.373
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
!SESSION 2016-02-29 23:09:12.620 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /var/webserver/workspace -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-02-29 23:09:24.115
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-02-29 23:09:24.115
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-03-01 02:57:37.181 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-03-01 02:58:57.238
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-03-01 02:58:57.239
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-03-04 12:15:00.941 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /var/webserver/workspace -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-03-04 12:22:18.610
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-03-04 12:22:18.610
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.eclipse.search 4 0 2016-03-04 12:40:50.401
!MESSAGE Problems encountered during text search.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.401
!MESSAGE File 'JokrBackend/JokrBackend/gunicorn.sock' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/gunicorn.sock'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/gunicorn.sock'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.403
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/gunicorn.sock'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.403
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/__pycache__/wsgi.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/wsgi.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/wsgi.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.403
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/wsgi.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.403
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/__pycache__/models.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/models.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/models.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.404
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/models.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.404
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/__pycache__/__init__.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/__init__.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/__init__.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.404
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/__init__.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.404
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/__pycache__/Constants.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/Constants.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/Constants.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.408
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/Constants.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.408
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/__init__.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/__init__.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/__init__.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.408
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/__init__.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.408
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/ProdSettings.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/ProdSettings.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/ProdSettings.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.408
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/ProdSettings.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.408
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/__init__.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/__init__.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/__init__.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.409
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/__init__.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.409
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/Notifier.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/Notifier.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/Notifier.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.409
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/Notifier.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.409
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/DataCollector.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/DataCollector.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/DataCollector.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.409
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/DataCollector.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.409
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/__init__.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/__init__.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/__init__.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.409
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/__init__.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.409
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/Utils.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/Utils.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/Utils.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.409
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/Utils.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-04 12:40:50.409
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/ModelFields.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/ModelFields.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/ModelFields.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-04 12:40:50.410
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/ModelFields.cpython-34.pyc'.
!SESSION 2016-03-08 19:09:02.583 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-03-08 19:09:16.628
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-03-08 19:09:16.629
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.eclipse.search 4 0 2016-03-08 19:25:13.385
!MESSAGE Problems encountered during text search.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.385
!MESSAGE File 'JokrBackend/JokrBackend/gunicorn.sock' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/gunicorn.sock'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/gunicorn.sock'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.386
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/gunicorn.sock'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.386
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/migrations/__init__.py' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/migrations/__init__.py'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/migrations/__init__.py'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.386
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/migrations/__init__.py'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.386
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/migrations/0001_initial.py' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/migrations/0001_initial.py'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/migrations/0001_initial.py'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.386
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/migrations/0001_initial.py'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.386
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/__pycache__/wsgi.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/wsgi.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/wsgi.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.390
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/wsgi.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.390
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/__pycache__/models.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/models.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/models.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.390
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/models.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.390
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/__pycache__/__init__.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/__init__.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/__init__.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.391
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/__init__.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.391
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/__pycache__/Constants.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/Constants.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/Constants.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.391
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/__pycache__/Constants.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.391
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/__init__.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/__init__.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/__init__.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.394
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/__init__.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.395
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/ProdSettings.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/ProdSettings.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/ProdSettings.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.395
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Settings/__pycache__/ProdSettings.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.395
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/__init__.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/__init__.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/__init__.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.395
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/__init__.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.395
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/Notifier.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/Notifier.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/Notifier.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.398
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/Notifier.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.398
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/DataCollector.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/DataCollector.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/DataCollector.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.398
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/DataCollection/__pycache__/DataCollector.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.398
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/__init__.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/__init__.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/__init__.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:40)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.399
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/__init__.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.399
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/Utils.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/Utils.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/Utils.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.399
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/Utils.cpython-34.pyc'.
!SUBENTRY 1 org.eclipse.search 4 4 2016-03-08 19:25:13.399
!MESSAGE File 'JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/ModelFields.cpython-34.pyc' has been skipped, problem while reading: ('Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/ModelFields.cpython-34.pyc'.').
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/ModelFields.cpython-34.pyc'.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:793)
	at org.eclipse.core.internal.resources.File.getContents(File.java:289)
	at org.eclipse.core.internal.resources.File.getContents(File.java:278)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.getInputStream(FileCharSequenceProvider.java:283)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.initializeReader(FileCharSequenceProvider.java:277)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.reset(FileCharSequenceProvider.java:269)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider$FileCharSequence.<init>(FileCharSequenceProvider.java:255)
	at org.eclipse.search.internal.core.text.FileCharSequenceProvider.newCharSequence(FileCharSequenceProvider.java:36)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFile(TextSearchVisitor.java:260)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.processFiles(TextSearchVisitor.java:196)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:172)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.search(TextSearchVisitor.java:184)
	at org.eclipse.search.core.text.TextSearchEngine$1.search(TextSearchEngine.java:56)
	at org.eclipse.search.internal.ui.text.FileSearchQuery.run(FileSearchQuery.java:182)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 2 org.eclipse.core.resources 4 274 2016-03-08 19:25:13.401
!MESSAGE Resource is out of sync with the file system: '/JokrBackend/JokrBackend/JokrBackend/Custom/__pycache__/ModelFields.cpython-34.pyc'.

!ENTRY org.python.pydev.shared_core 4 4 2016-03-08 19:54:24.256
!MESSAGE Marker id 152094 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 152094 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:98)
	at org.python.pydev.debug.model.PyBreakpoint.getType(PyBreakpoint.java:155)
	at org.python.pydev.debug.model.AbstractDebugTarget.breakpointRemoved(AbstractDebugTarget.java:352)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.run(BreakpointManager.java:995)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.notify(BreakpointManager.java:1018)
	at org.eclipse.debug.internal.core.BreakpointManager.fireUpdate(BreakpointManager.java:932)
	at org.eclipse.debug.internal.core.BreakpointManager.removeBreakpoints(BreakpointManager.java:503)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointManagerVisitor.update(BreakpointManager.java:754)
	at org.eclipse.debug.internal.core.BreakpointManager.resourceChanged(BreakpointManager.java:688)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:146)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.core.resources 4 376 2016-03-08 19:54:24.256
!MESSAGE Marker id 152094 not found.
!SESSION 2016-03-08 21:39:52.522 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.jface 2 0 2016-03-08 21:40:44.680
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-03-08 21:40:44.680
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SESSION 2016-03-09 14:02:18.667 -----------------------------------------------
eclipse.buildId=debbuild
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2016-03-09 14:02:20.546
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.jface 2 0 2016-03-09 14:02:36.982
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2016-03-09 14:02:36.982
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,com.python.pydev.analysis.actions.PyGlobalsBrowserWorkbench),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		ActionDelegateHandlerProxy(null,org.python.pydev.editor.actions.PyShowBrowser),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.python.pydev.shared_core 4 4 2016-03-09 21:47:04.218
!MESSAGE No message gotten (null message).
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1055)
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1182)
	at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:137)
	at org.eclipse.jface.text.AbstractDocument.getLineInformation(AbstractDocument.java:929)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineInformation(SynchronizableDocument.java:337)
	at org.python.pydev.shared_core.string.TextSelectionUtils.getStartLine(TextSelectionUtils.java:164)
	at org.python.pydev.editor.refactoring.RefactoringRequest.getBeginCol(RefactoringRequest.java:201)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:76)
	at com.python.pydev.refactoring.refactorer.RefactorerFindDefinition.findDefinition(RefactorerFindDefinition.java:61)
	at com.python.pydev.refactoring.refactorer.Refactorer.findDefinition(Refactorer.java:114)
	at com.python.pydev.refactoring.wizards.rename.PyReferenceSearcher.prepareSearch(PyReferenceSearcher.java:106)
	at com.python.pydev.refactoring.markoccurrences.MarkOccurrencesJob.createRequest(MarkOccurrencesJob.java:147)
	at org.python.pydev.shared_ui.mark_occurrences.BaseMarkOccurrencesJob.run(BaseMarkOccurrencesJob.java:168)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 4 4 2016-03-09 21:57:01.769
!MESSAGE No message gotten (null message).
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1055)
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1182)
	at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:137)
	at org.eclipse.jface.text.AbstractDocument.getLineInformation(AbstractDocument.java:929)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineInformation(SynchronizableDocument.java:337)
	at org.python.pydev.shared_core.string.TextSelectionUtils.getStartLine(TextSelectionUtils.java:164)
	at org.python.pydev.editor.refactoring.RefactoringRequest.getBeginCol(RefactoringRequest.java:201)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:76)
	at com.python.pydev.refactoring.refactorer.RefactorerFindDefinition.findDefinition(RefactorerFindDefinition.java:61)
	at com.python.pydev.refactoring.refactorer.Refactorer.findDefinition(Refactorer.java:114)
	at com.python.pydev.refactoring.wizards.rename.PyReferenceSearcher.prepareSearch(PyReferenceSearcher.java:106)
	at com.python.pydev.refactoring.markoccurrences.MarkOccurrencesJob.createRequest(MarkOccurrencesJob.java:147)
	at org.python.pydev.shared_ui.mark_occurrences.BaseMarkOccurrencesJob.run(BaseMarkOccurrencesJob.java:168)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

!ENTRY org.python.pydev.shared_core 4 4 2016-03-09 23:09:52.150
!MESSAGE String index out of range: 51
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 51
	at java.lang.String.substring(String.java:1907)
	at org.python.pydev.core.docutils.PySelection.getTextForCompletionInConsole(PySelection.java:890)
	at org.python.pydev.debug.newconsole.PydevConsoleInterpreter.getDescription(PydevConsoleInterpreter.java:243)
	at org.python.pydev.shared_interactive_console.console.ui.DefaultScriptConsoleTextHover.getHoverInfoImpl(DefaultScriptConsoleTextHover.java:30)
	at org.python.pydev.shared_interactive_console.console.ui.AbstractScriptConsoleTextHover.getHoverInfo(AbstractScriptConsoleTextHover.java:22)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:168)

!ENTRY org.python.pydev.shared_core 4 4 2016-03-09 23:28:55.858
!MESSAGE Marker id 153475 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 153475 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:98)
	at org.python.pydev.debug.model.PyBreakpoint.getType(PyBreakpoint.java:155)
	at org.python.pydev.debug.model.AbstractDebugTarget.breakpointRemoved(AbstractDebugTarget.java:352)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.run(BreakpointManager.java:995)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointNotifier.notify(BreakpointManager.java:1018)
	at org.eclipse.debug.internal.core.BreakpointManager.fireUpdate(BreakpointManager.java:932)
	at org.eclipse.debug.internal.core.BreakpointManager.removeBreakpoints(BreakpointManager.java:503)
	at org.eclipse.debug.internal.core.BreakpointManager$BreakpointManagerVisitor.update(BreakpointManager.java:754)
	at org.eclipse.debug.internal.core.BreakpointManager.resourceChanged(BreakpointManager.java:688)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:146)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.core.resources 4 376 2016-03-09 23:28:55.859
!MESSAGE Marker id 153475 not found.
